### PR TITLE
Port docs from Wiki to Docusaurus

### LINKED ISSUE #648: Move docs from wiki to Docusaurus
## Description
Right now, the whole Portal docs is in rhe repository [wiki](https://github.com/anitab-org/portal/wiki).

We will now move to Docusaurus (https://v2.docusarus.io)

TODO:
- [x] Add a basic minimal scaffold in `docs/` (use [Tinysaurus](https://github.com/SanketDG/tinysaurus/))
- [x] Remove the old files from `docs/`
- [ ] Remove any dependencies for the old docs. (`sphinx` for example)
- [x] Convert all the markdown files from `wiki` and put it in `docs`
- [x] Categorize the Documentation in the right places
- [ ] Add any extra Documentation (can be done post-merge)
- [ ] Update the Footer
- [ ] Deploy Strategy
    - Netlify?
    - Vercel?

### PR DESCRIPTION
**Pull request by SanketDG**
## Description
Right now, the whole Portal docs is in rhe repository [wiki](https://github.com/anitab-org/portal/wiki).

We are moving to Docusaurus (https://v2.docusarus.io)

**Preview**: [anitab-portal.surge.sh](https://anitab-portal.surge.sh)

TODO:
- [x] Add a basic minimal scaffold in `docs/` (use [Tinysaurus](https://github.com/SanketDG/tinysaurus/))
- [x] Remove the old files from `docs/`
- [ ] Remove any dependencies for the old docs. (`sphinx` for example)
- [x] Convert all the markdown files from `wiki` and put it in `docs` (Thanks to @sakshi1499 for doing the heavy lifting :tada:)
- [x] Categorize the Documentation in the right places
- [x] Add any extra Documentation (can be done post-merge)
- [x] Update the Footer
- [ ] Deploy Strategy
    - Netlify?
    - Vercel?

Closes #648

_We are mostly looking for comments on what goes in and what goes out of the whole porting. We won't add any documentation right now, (this may be done through future contributors)_

_We have also decided to not keep anything that is ephemeral, so nothing specific to GSoC or any other program_

### CODE REVIEW

**Comment by isabelcosta** [comment]
I've quickly checked the preview, and this is amazing :D 👏 👏 👏

**Review by ritwickraj78 — APPROVED** [review]

**Review by sammy1997 — APPROVED** [review]
Looks great!

**Review by satya7289 — COMMENTED** [review]
Looks great..!!.
For the deployment purpose we can use GitHub pages, no need to maintain extra server..

I really excited to know why are you choosing Docusaurus, however there are many alternatives available like mkdocs(provides many themes) where no need to convert .md files to docs , can also be deployed like GitHub pages, etc..!!!

**Comment by SanketDG** [comment]
> For the deployment purpose we can use GitHub pages, no need to maintain extra server..

We were thinking of going with Netlify or Vercel which are just better GH Pages :smile: 

> however there are many alternatives available like mkdocs(provides many themes) where no need to convert .md files to docs , can also be deployed like GitHub pages, etc..!!!

> where no need to convert .md files to docs 

We converted the Wiki's to `.md`, I am not sure what you mean here.

Any SSG for that matter does the same, just outputs a bunch of html/css/js files, I think we went with Docusaurus, because of UI and accessiblility.

**Comment by sammy1997** [comment]
@sakshi1499 @mayburgos Can you add your reviews so that we can merge this?

**Comment by mayburgos** [comment]
> @sakshi1499 @mayburgos Can you add your reviews so that we can merge this?

Please move forward without my review, thank you!

**Comment by sakshi1499** [comment]
@sammy1997 I didn't want to approve our own PR. Can you please go ahead and merge this?

**Comment by annabauza** [comment]
@SanketDG can you please tell me if I can host it on github static pages? If yes what do I need to do to prepare static page?

**Comment by SanketDG** [comment]
@annabauza 

> can you please tell me if I can host it on github static pages? If yes what do I need to do to prepare static page?

```
$ yarn build
```

should put the static files in `build/` folder, which can just be uploaded to github pages.

The rest of the instructions are in the README.

**Comment by annabauza** [comment]
I figured it out thanks

**Pull request merged**
