### PR TITLE
Integrate commitlint with Github Actions

### PR DESCRIPTION
**Pull request by SanketDG**
This PR uses `commitlint` to lint commit messages to follow our [commit guidelines](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide) using Github Actions

### CODE REVIEW

**Comment by sammy1997** [comment]
Awesome tool!! Really cool...Didn't know this existed

**Comment by sammy1997** [comment]
@SanketDG Can you send one with the proper tag? Like chore or something?

**Review by sammy1997 — APPROVED** [review]
LGTM!! We can merge this

**Review by sakshi1499 — APPROVED** [review]
LGTM

**Pull request merged**
