### PR TITLE
added request meetup location to meetup dropdown

### LINKED ISSUE #366: Position the "Request a New Meetup Location" into the meetups dropdown.
## Description
As a user, I need to see a "Request a New Meetup Location" on the meetups dropdown and not on the meetup location sidebar, so that it's similar to that of "Request communities" and independent of any meetup location page.

### Update [Required]
- [ ] Position the "Request a New Meetup Location" into the meetups dropdown.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
< 1 hour

### PR DESCRIPTION
**Pull request by Fenn-CS**
Signed-off-by: Fenn-25 <fenn25.fn@gmail.com>

### Description
Added request meetup location and view meetup location requests (for staff) in meetup dropdown

Fixes #366 

dropdown added

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
All test passed locally.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ajatprabha** [comment]
@Fenn-CS There are many whitespace changes. Can you fix it and just commit the issue specific changes?

**Comment by Fenn-CS** [comment]
@ajatprabha ok... Noticed that! Was just lazy :)

**Comment by ajatprabha** [comment]
@Fenn-CS The original issue says, it's not required to include the link in sidebar also. Perhaps @sa7i can tell more. Otherwise this looks good to me.

**Comment by Fenn-CS** [comment]
@ajatprabha yeah you right, I thought of removing it but for a minute I wondered if theres really a problem with the links appearing at the sidebar. Don't you think it increases accessibility options? @systers/maintainers-portal ideas please? It this ok?

**Pull request merged**
