### PR TITLE
docs: add Zulip chat badge to README

### LINKED ISSUE #600: Add a badge to join Zulip chat on README
## Description

As a new contributor,
I need know which chat can I join regarding this project,
so that I can discuss this project with the community.

I did something similar in here https://github.com/anitab-org/mentorship-backend/pull/683

## Mocks

image

### Update [Required]
- [ ] Add Zulip chat badge to README with link to Zulip stream dedicated to #vms (Link: https://anitab-org.zulipchat.com/#narrow/stream/222540-portal)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by SHITIZ-AGGARWAL**
### Description

Fixes #600 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@isabelcosta can you please tell if I did something wrong

**Review by SanketDG — DISMISSED** [review]
LGTM!

**Comment by SanketDG** [comment]
@SHITIZ-AGGARWAL Can you follow the [commit message guidelines](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide)?

**Comment by SHITIZ-AGGARWAL** [comment]
@SanketDG sure ,I will keep that in mind
should I commit once again ??

**Review by isabelcosta — DISMISSED** [review]
Great work @SHITIZ-AGGARWAL 👏

**Comment by isabelcosta** [comment]
@SHITIZ-AGGARWAL if you can amend the commit and change the message that is good, but if you struggle with it, @SanketDG or I can do that when squashing and merging.

**Comment by SHITIZ-AGGARWAL** [comment]
@isabelcosta I tried but I am having problem in commit message ,if you could please amend it that would be a great help
I am new to open source and git

**Review by isabelcosta — APPROVED** [review]

**Review by SanketDG — APPROVED** [review]
LGTM!

**Pull request merged**
