### PR TITLE
fix: removed F405 from setup.cfg

### LINKED ISSUE #608: Fix F405 flake8 error.
## Description
As a developer,
I need to fix flake8 error,
so that F405 can be removed from set.cfg.

It should be taken after this [PR](https://github.com/anitab-org/portal/pull/578) get merged
## Mocks

Screenshot from 2020-07-22 19-20-01

Screenshot from 2020-07-22 11-16-47

## Acceptance Criteria
F405 should be removed from setup.cfg file.

### Update [Required]
-  F405 should be removed from setup.cfg file and above error should be fixed.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by Harshita-Kanal**
Signed-off-by: Harshita-Kanal <harshita.kgv@gmail.com>

### Description
Removed F405 from setup.cfg
Fixes #608 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Harshita-Kanal** [comment]
The tests are failing, what changes should I make ?

**Comment by SanketDG** [comment]
@Harshita-Kanal That's on you to figure out, read what F405 means and how it's breaking flake8

Let me know if you can't figure it out.

**Comment by sakshi1499** [comment]
@Harshita-Kanal Working on it?

**Comment by sakshi1499** [comment]
Closing this PR since there is no activity. Hope you get back soon :)

**Pull request closed without merging**
