### PR TITLE
meetup - gsoc'16 work

### PR DESCRIPTION
**Pull request by payal97**
remaining commits for work completed during gsoc'16

### CODE REVIEW

**Comment by payal97** [comment]
There are a few more commits left. I'll push them as soon as possible. Thanks a lot for your patience!

**Comment by payal97** [comment]
@tapasweni-pathak 
These are the remaining commits for the work I completed.
Support requests are one feature which I had worked on, but during the final evaluation it was suggested to change its overall structure and use. We can discuss how exactly we need this feature to be and someone else or myself can work on this further.

**Comment by payal97** [comment]
Please let me know if further changes to this work are required.

**Comment by payal97** [comment]
@tapasweni-pathak For sending email notifications to user groups, I used '[pinax-notifications](https://github.com/pinax/pinax-notifications/tree/master)'. One of the models in that has a ForiegnKey to 'settings.AUTH_USER_MODEL' which is not specified in our settings file, so the travis build is failing. I didn't get the error in my system earlier, while using python 2.7 and django 1.7.7, so I went ahead with 'pinax-notifications'. How should I continue with this? Should I remove 'pinax-notifications' entirely and look for other ways to send the notifications?

**Comment by tapasweni-pathak** [comment]
>These are the remaining commits for the work I completed.
Support requests are one feature which I had worked on, but during the final evaluation it was suggested to change its overall structure and use. We can discuss how exactly we need this feature to be and someone else or myself can work on this further.

Is this not complete?

**Comment by payal97** [comment]
Though it is complete, in the current form, the support request is created by the volunteer. For example, if someone can provide any form of assistance for a meetup, they will create a support request which the organizers can comment on and discuss with them. The organizers can eventually accept or reject the request.
It was suggested that it should be something that the meetup organizers create, which members can volunteer for.

This is what it currently looks like:
screenshot 2017-12-15 20 39 25

We can perhaps change the permissions for adding support requests, and add options to 'assign volunteer'.

**Comment by tapasweni-pathak** [comment]
@payal97 First you need to fix the Travis error, then we merge this one. Please then raise issues where you see a scope of improvement w/ your work. This has always been the case that summer/winter of code intern creates issues about what can be further improved. Happy to take in all the suggestions. :)

**Comment by tapasweni-pathak** [comment]
so I guess @payal97 didn't get the time for this, no worries. @sa7i do you see a quick fix w/ this one?

**Comment by sa7i** [comment]
@tapasweni-pathak I resolved the issue by downgrading pinax-notifications.
Update requirements/dev.txt with `pinax-notifications==2.0.1` 
I can later upgrade pinax-notifications in #201 

Refs: https://stackoverflow.com/questions/30286266/dependencies-references-nonexistent-parent-node-error-after-pinax-notificatio

**Comment by payal97** [comment]
@tapasweni-pathak @sa7i 
The problem I'm facing is in specifying the AUTH_USER_MODEL. It should be of the form 'app_label.model_name', where the app_label is also specified in installed apps. The default user is the User model in django.contrib.auth, but on specifying AUTH_USER_MODEL as 'django.contrib.auth.User' it gives an ImproperlyConfigured error. I tried labeling django.contrib.auth as something else, but it didn't work. I'm still looking for other solutions, but couldn't find anything so far.

Meanwhile should I open a separate pull request for notifications, so that the rest of the code can be merged?

**Comment by payal97** [comment]
@sa7i  I just saw your comment. Glad that it was resolved.

**Comment by sa7i** [comment]
@payal97 could you update your requirements/dev.txt with this https://github.com/systers/portal/pull/291/files to resolve the pip error

**Comment by payal97** [comment]
@sa7i sure, I'll do that.

**Comment by tapasweni-pathak** [comment]
Thanks for working together on this @payal97, @sa7i! 

@payal97 it would be great if you can raise issues where you see this can be further improved.

**Pull request merged**
