### PR TITLE
Migrating Portal from django1.7 to 1.11 and upgrading other packages

### LINKED ISSUE #201: Migrate to Django version 1.11 and Python 3.6
With latest version of OS, >Ubuntu 16.04, Debian 9 Stretch having Python >= 3.5, Django 1.7.7 is having issues.

```
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
```
because HTMLParseError is deprecated from Python 3.3 onwards and removed with Python 3.5. Temporary fix of this [not a good option] is to downgrade Python version or a better way is to upgrade Django version to >1.7. Also with Django 1.8 in guardian/admin.py change ```module_name``` to ```model_name``` at all its occurrences.

Migrate portal to newer Django version, 1.11.

**W/ this also move all used packages in Portal to latest and compatible one.** https://github.com/systers/portal/issues/290

### PR DESCRIPTION
**Pull request by sa7i**
Fixes #201.

This PR solves #201 
All packages other than flake8 has been updated to their latest versions. 
Other than urls.py and settings files, Tests also had to be modified. 
EDIT:
To test this,
I created a new virtual environment `virtualenv venv --python=/path/to/python3.6 --no-site-packages`, deleted the old one.
After activating this venv, I installed all the packages from the requirements using `pip -r install requirements/dev.txt` 
And when it's time to migrate, I was facing errors like `django.db.utils.programmingerror relation already exists` , so I faked migrations using[ this](https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-migrate-fake-initial) `python manage.py migrate --fake-initial`. I was getting these errors because I was already having a systersdb database. 
Once, you migrate you can run `python manage.py runserver`

### CODE REVIEW

**Comment by sa7i** [comment]
Hi, when I was testing, I too faced issues during migration, so I faked the migrations using
 `python manage.py migrate --fake-initial`. 
I didn't modify any files though, I just faked the migrations and it seemed to work. 
It didn't strike my mind to put this into the description before because I was thrilled that it's working. :-p

**Comment by tapasweni-pathak** [comment]
> Hi, when I was testing, I too faced issues during migration, so I faked the migrations using
python manage.py migrate --fake-initial.
I didn't modify any files though, I just faked the migrations and it seemed to work.
It didn't strike my mind to put this into the description before because I was thrilled that it's working. :-p

👍 

@sa7i You missed the first question. :(

**Comment by sa7i** [comment]
I didn't include user=None in clean_password in adapter.py after migrating to newer django-allauth

**Comment by tapasweni-pathak** [comment]
> I didn't include user=None in clean_password in adapter.py after migrating to newer django-allauth

While signing up did this pop up on your console?
```TypeError: clean_password() got an unexpected keyword argument 'user'```

**Comment by sa7i** [comment]
I just checked. I got the error @tapasweni-pathak

**Comment by tapasweni-pathak** [comment]
This is a important change, can you edit your commit messages and be a bit more descriptive there? These will sit in the log. Also squash the last one with something else. Then we are good to go with this! 🚀

**Comment by MeepyMay** [comment]
@tapasweni-pathak @sa7i What is the current status on this PR? There are a few contributors wanting to help but there's a lot of confusion on the compatibility.

**Comment by sa7i** [comment]
@MeepyMay @tapasweni-pathak Sorry for the delay. I have edited my commit messages, Please review this.

**Comment by tapasweni-pathak** [comment]
> There are a few contributors wanting to help but there's a lot of confusion on the compatibility.

@MeepyMay Please share with them that they can go ahead and submit their work as pull request. With Portal they shouldn't be having any compatibility issue. With VMS, they may.

**Comment by sa7i** [comment]
I am taking into account the commits that are getting merged in the portal repo.

**Comment by tapasweni-pathak** [comment]
> post_migrate signal isn't even getting connected during testing. post_migrate signal has to be connected to create the NoticeTypes.

@sa7i can you please elaborate more on "connected"? If we are not able to resolve this we'll remove pinax completely, it is not priority.

**Comment by sa7i** [comment]
@tapasweni-pathak I removed pinax-notifications by reverting the commit https://github.com/systers/portal/commit/e81652fcba9a6705f4926bb8089bf92821e03ee6 Please review this.

**Comment by sa7i** [comment]
Thank you @tapasweni-pathak 👏

**Pull request merged**
