### PR TITLE
test: Subscription Tests Added

### LINKED ISSUE #641: Tests for Subscription and Suggested Meetup features
## Description
As a developer,
I need to add sufficient tests,
so that coverage targets can be met.

### Update [Required]
- [ ] Add tests to cover the code added for Subscription feature
- [ ] Add tests to cover the code added for Suggested Meetup feature

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-6 days

### PR DESCRIPTION
**Pull request by ritwickraj78**
### Description
Tests for the features added.

Fixes #641 

### Type of Change:
**Delete irrelevant options.**

- Code

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by ritwickraj78** [comment]
@SanketDG I am unable to figure out why one of the tests seem to fail. Could you please check it out?

**Comment by SanketDG** [comment]
I don't know why but Google-fu says to change https://github.com/anitab-org/portal/blob/8110f63d7c004d73562814620d84f01d1b08a5d0/systers_portal/users/models.py#L196 

to

```
models.ForeignKey(SystersUser)
```

**Comment by sammy1997** [comment]
@ritwickraj78 can you resolve this? We can merge it then! Let us know if the issue is resolved by what @SanketDG has mentioned

**Comment by ritwickraj78** [comment]
@sakshi1499 @SanketDG @sammy1997 Please have a look

**Review by sammy1997 — APPROVED** [review]
LGTM. @SanketDG @sakshi1499 Please approve and merge....I am not sure about the patch configuration

**Review by sakshi1499 — APPROVED** [review]
@SanketDG What do you think should we merge? I think we can as it looks good other than that patch error.

**Review by SanketDG — APPROVED** [review]
Looks good to me

**Pull request merged**
