### PR TITLE
enh: Remove Systers' Logo

### LINKED ISSUE #546: Remove Systers' Logo
## Description
As a user,
only AnitaB.org logo should be visible.

## Mocks
image

## Acceptance Criteria
Systers Logo should be removed.
 
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by gaurivn**
### Description
Removed Systers' Logo

Fixes #546 

### Type of Change:
**Delete irrelevant options.**

- User Interface

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
Screenshot from 2020-06-16 12-22-21

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by sakshi1499** [comment]
Is it as it looks in the screenshot? Because that looks really stretched @gaurivn

**Comment by sammy1997** [comment]
@gaurivn can you squash the 2 commits?

**Comment by gaurivn** [comment]
> Is it as it looks in the screenshot? Because that looks really stretched @gaurivn

Yes, I took the screenshot of running website after I cropped out Systers' logo.

**Comment by gaurivn** [comment]
> @gaurivn can you squash the 2 commits?

Sure

**Review by theyashshahs — COMMENTED** [review]
@gaurivn the logo looks a bit stretched, can you take a higher resolution image :)

**Review by sammy1997 — COMMENTED** [review]
We should use a better resolution image or use something like .webp

**Review by sakshi1499 — COMMENTED** [review]
I'll see if I can look for a better resolution image. I'll link the file in the comments. If it isn't available we'll see for some other alternative, it currently looks really stretched.

**Comment by sakshi1499** [comment]
@gaurivn Were you able to find better resolution logo?

**Comment by gaurivn** [comment]
Sorry for the delay, I got a few AnitaB.org logos - better resolution ones, I'll try with them.

**Comment by sakshi1499** [comment]
@gaurivn awesome. Sure ☺️

**Comment by sakshi1499** [comment]
@gaurivn Any updates?

**Comment by sakshi1499** [comment]
Can you add a photo of how it looks now?

**Comment by gaurivn** [comment]
I think I don't have the bandwidth for this atm..faced some issues while trying to run again after changing logos.. closing this PR and making it available.

**Pull request closed without merging**
