### PR TITLE
Updated Twitter Link on contact page

### PR DESCRIPTION
**Pull request by Adeola-Adesoba**
### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Updated Twitter Link on contact page

Fixes # [585]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by SanketDG — DISMISSED** [review]
LGTM apart from updating your commit message to https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide!

**Comment by sakshi1499** [comment]
@adeola-adesoba Can you please update the commit according to the commit guidelines as mentioned by Sanket?

**Comment by sakshi1499** [comment]
@adeola-adesoba The title should be fix and not doc. Sorry, can you make that change?

**Comment by Adeola-Adesoba** [comment]
> @Adeola-Adesoba The title should be fix and not doc. Sorry, can you make that change?

I can but please, let me know what else need to be on there before I do that. Thanks.

**Review by SanketDG — APPROVED** [review]
This looks great @Adeola-Adesoba!

**Review by sakshi1499 — APPROVED** [review]
LGTM :)

**Pull request merged**
