### PR TITLE
Enter character is now reflected in comments

### LINKED ISSUE #348: New lines not being visible in the comments.
## Description
As a [USER],
I need [to comment in the discussion area and hit enter to start off the next piece of text in the second line],
so that I can [].

## Mocks
screenshot from 2018-03-08 20-54-39

### Update [Required]
- [ ] [When I press enter while feeding comments the new line texts should be visible on separate lines.]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[15] minutes

### PR DESCRIPTION
**Pull request by abhi20161997**
### Description
When we hit enter while entering or editing any comments in the discussion area , the new line is now seen in the comments

Fixes #348

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
screenshot from 2018-03-21 16-36-15

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abhi20161997** [comment]
@sa7i @tapasweni-pathak @Janiceilene  Please review this.

**Comment by pavankm** [comment]
- Not a breaking change
- Font family does not change due to CSS.

This change seems good to go.

**Comment by sa7i** [comment]
@abhi20161997 You could remove the space between # and 348 to link this PR to the issue.
Pressing enter is working fine with this change, but it'd be nice, if this could be done without changing the css on textbox (the grey box that's getting created)

**Comment by abhi20161997** [comment]
@sa7i  -implemented your changes. Please can you have a look.

**Comment by sa7i** [comment]
Thank you for the changes.
I haven't noticed it before, but the font of the comments is changing. Could this be done without the font change? 
image

**Comment by sa7i** [comment]
This looks good. Thanks for the work.

**Pull request merged**
