### PR TITLE
feat: Create config file for welcome bot

### LINKED ISSUE #649: Create the config.yml file for the Welcome Bot
## Description
 As a first time contributor,
 I need a bot to help guide my first contribution,
 so that I can follow this org's contribution guidelines.
 
 ## Mocks
 Screen Shot 2020-08-06 at 10 26 14 AM
 
 ## Acceptance Criteria
 ### Update [Required]
 * [ ]  newIssueWelcomeComment is complete with the correct links to this repo.
 * [ ]  newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
 * [ ]  firstPRMergeComment is complete.
 
 ## Definition of Done
 * [ ]  All of the required items are completed.
 * [ ]  Approval by 1 mentor.
 
 ## Estimation
 0.5 hours

### PR DESCRIPTION
**Pull request by m-code12**
### Description
Created config.yml file for the welcome bot to help first-time contributors. To activate the app you need to go to https://github.com/apps/welcome and click on install and give the app the required permissions.( Can only be done by a member of the org)

Fixes #649 

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
[x] Bug fix (non-breaking change which fixes an issue)
[x] New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I have tested the welcome bot with the same config.yml file in my personal repository. Here is a link to the repo:
https://github.com/m-code12/WelcomeBot

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by m-code12** [comment]
@SanketDG Please could you review this pr?

**Review by sakshi1499 — COMMENTED** [review]
@m-code12 Your commit message is failing please follow the commit guidelines.

**Comment by m-code12** [comment]
@sakshi1499 I have amended the commit message, even then it's failing.
What should I do, could you help me out?

**Comment by m-code12** [comment]
I am trying again and again but still the commit check is failing.
If you could amend it from your end it would be of great help @sakshi1499 @SanketDG

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@m-code12 see your first commit "Create config.yml for Welcome Bot". It is missing a type. Also, it would be better if you squash your commits first into one. 
The merge commit will have the same issue

**Comment by m-code12** [comment]
@sakshi1499 @devkapilbansal I am closing this pr and have opened a new pr #690 where all the checks have passed.

**Pull request closed without merging**
