### PR TITLE
remove djangocms_admin_style from requirements

### LINKED ISSUE #587: Remove djangocms-admin-style from package dependencies
## Description

Back in 1.11, the Django admin UI did not look good at all, hence the reason why a better admin styling package was used.

Things have changed now in 3.0, Django comes with a prettyish admin UI, so this package is not needed and can be removed.

When #578 is merged, we are going to use Django's default new UI.

## Tasks
- [ ] Remove `djangocms-admin-style` from requirements
- [ ] Remove from settings.py

_I'd be interested in mentoring someone formally since this is relatively easy. Please ping me on Zulip if you are relatively new here and you want to get started with your first PR!_

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by morrme**
### Description
Removed djangocms_admin_style from the package requirements as requested by @SanketDG 

Fixes #587 
### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x ] My PR follows the style guidelines of this project

### CODE REVIEW

**Review by SanketDG — COMMENTED** [review]
Great job! If you could just follow the [commit message guidelines](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide), and amend the messages, I will merge this!

**Comment by morrme** [comment]
> Great job! If you could just follow the [commit message guidelines](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide), and amend the messages, I will merge this!

@SanketDG  Done!

**Review by sakshi1499 — APPROVED** [review]
Lgtm

**Review by SanketDG — APPROVED** [review]
LGTM

**Pull request merged**
