### PR TITLE
Feature: Revamped Meetup Search

### LINKED ISSUE #541: Meetup Search page UI revamp
## Description
As a user,
I need a better meetup search interface, without the date field and with a distance similar to [Meetup.com](https://www.meetup.com) event search page.

## Mocks
ss_search

### Update [Required]
- [ ] Remove meetup location dropdown
- [ ] Remove date field. Sort results by date as a defaut
- [ ] Remove date filter, keep a distance filter
- [ ] Keep a current location or typed location based search

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor and an admin.

## Estimation
3-4 days

### PR DESCRIPTION
**Pull request by ritwickraj78**
### Description
- Removed Date Time Filters
- Removed meetup location field
- Modified location field

Fixes #541 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
All unit tests and CI test passes. Tested locally on the system.
ezgif com-video-to-gif (1)

ezgif com-video-to-gif
### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SanketDG — CHANGES_REQUESTED** [review]
This is superseded by #572 right?

**Comment by ritwickraj78** [comment]
Yes @SanketDG

**Comment by SanketDG** [comment]
Can we close this then?

**Comment by ritwickraj78** [comment]
There are two different issues and hence two different PRs IG. If there is no problem with closing two issues with one PR, then it is fine on my part

**Comment by SanketDG** [comment]
Unless you actually divide the work between the two PRs, there's no point sticking to this rule. If you want to follow the rule, you can put the respective commits here and we merge this, or we can close this and make #572 close both the issues (which is fine IMO)

Willing to have some input from you and the other mentors as well

**Comment by sakshi1499** [comment]
I agree with @SanketDG on this. I think it is a rule to have one PR per issue, but it doesn't make sense here. I'll suggest we close this and merge the other one while closing both the issues.

**Comment by sammy1997** [comment]
@ritwickraj78 @SanketDG @sakshi1499 We can close this. But @ritwickraj78 I would suggest making PRs from the updated develop branch if the 2 PRs are not linked. I can see that the other PR only has 2 changed files and is independent of this one. SO you can decouple them going ahead

**Pull request closed without merging**
